[tool.poetry]
name = "clone of deep-research"
version = "0.1.0"
description = ""
authors = ["nam pham <contact.nampham.work@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
